# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
        args: ['--maxkb=500']
      - id: check-toml
      - id: check-yaml
        args:
          - --unsafe
      - id: check-json
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending
        args: ['--fix=lf']

  - repo: local
    hooks:
      - id: ruff-check
        name: ruff check
        entry: ruff check --force-exclude --fix --exit-non-zero-on-fix
        language: system
        types: [python]
        require_serial: true

      - id: ruff-format
        name: ruff format
        entry: ruff format --force-exclude
        language: system
        types: [python]
        require_serial: true

      - id: mypy
        name: mypy type check
        entry: mypy src/mtn_cloud
        language: system
        types: [python]
        pass_filenames: false
        require_serial: true

